version: "3"

services:
  app:
    container_name: app
    image: node_app:latest
    restart: always
    build: .
    ports:
      - "8888:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27016:27017"
